name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: cedrickring/golang-action@1.3.0
    - name: Run build & test
      run: |
        go test
        go build
